import Footer from "../components/nav/Footer";
import Navbar from "../components/nav/Navbar";
import { menu } from "../data/menu";
import "./globals.css";

export const metadata = {
  title: "Eric Kulbiej - Frontend Developer, Researcher, and Seafarer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content={metadata.description} />
        <meta name="author" content="Eric Kulbiej" />
        <meta name="keywords" content="Eric Kulbiej, Frontend Developer, Researcher, Writer" />
        <link rel="icon" href="/logo512.png" />
        <title>{metadata.title}</title>
      </head>
      <body>
        <nav>
          <Navbar data={menu}/>
        </nav>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
